<?php
namespace Database\Seeders;

use App\Models\Personnel;
use Illuminate\Database\Seeder;

class PersonnelSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //Personnel::factory()->count(10)->create();
        $sra      = 'Science Research Analyst';
        $srs1     = 'Science Research Specialist I';
        $srs2     = 'Science Research Specialist II';
        $ssrs     = 'Senior Science Research Specialist';
        $supersrs = 'Supervising Science Research Specialist';
        $laborer  = 'Laborer';
        $jo       = 'Job Order';
        $aa       = 'Administrative Assistant';

        $personnels = [
            [
                'lname'       => 'Administrator',
                'fname'       => 'DA-CBC',
                'mname'       => null,
                'suffix'      => null,
                'position'    => 'Administrator',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '00-0000',
            ],
            [
                'lname'       => 'ACHUELA',
                'fname'       => 'Amabel',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-0304',
            ],
            [
                'lname'       => 'AGUILAR',
                'fname'       => 'Glorilyn',
                'mname'       => 'R.',
                'suffix'      => null,
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-0721',
            ],
            [
                'lname'       => 'AGUSTIN',
                'fname'       => 'Nonawin',
                'mname'       => 'L.',
                'suffix'      => null,
                'position'    => $supersrs,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '11-0819',
            ],
            [
                'lname'       => 'ANTOLIN',
                'fname'       => 'Wilfrado',
                'mname'       => 'DC.',
                'suffix'      => null,
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '03-0219',
            ],
            [
                'lname'       => 'AVILA',
                'fname'       => 'Julius',
                'mname'       => 'M.',
                'suffix'      => null,
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '18-1120',
            ],
            [
                'lname'       => 'BALAY',
                'fname'       => 'Everlito',
                'mname'       => 'Jr.',
                'suffix'      => 'Jr.',
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-0517',
            ],
            [
                'lname'       => 'BOADA',
                'fname'       => 'Roel',
                'mname'       => null,
                'suffix'      => null,
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-1131',
            ],
            [
                'lname'       => 'BRILLO',
                'fname'       => 'Niña Michaela',
                'mname'       => null,
                'suffix'      => null,
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1230',
            ],
            [
                'lname'       => 'CALANDAY',
                'fname'       => 'Roseann Mae',
                'mname'       => 'B.',
                'suffix'      => null,
                'position'    => $aa,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0539',
            ],
            [
                'lname'       => 'CALDERON',
                'fname'       => 'Mar Amiel',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $jo,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1216',
            ],
            [
                'lname'       => 'CATALON',
                'fname'       => 'Henry',
                'mname'       => 'C.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '16-0761',
            ],
            [
                'lname'       => 'COMBE',
                'fname'       => 'Josephine',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1207',
            ],
            [
                'lname'       => 'CORPUZ',
                'fname'       => 'Hircoles',
                'mname'       => 'B.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '12-0206',
            ],
            [
                'lname'       => 'CRUZ',
                'fname'       => 'Cheicelle Daine',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1021',
            ],
            [
                'lname'       => 'CRUZ',
                'fname'       => 'Antoinette',
                'mname'       => 'S.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '17-0743',
            ],
            [
                'lname'       => 'DAROLLO',
                'fname'       => 'Jean',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1042',
            ],
            [
                'lname'       => 'DATANG',
                'fname'       => 'Nelson',
                'mname'       => 'D.',
                'suffix'      => null,
                'position'    => $laborer,
                'address'     => null,
                'email'       => null,
                'employee_id' => '10-0716',
            ],
            [
                'lname'       => 'DE GUZMAN',
                'fname'       => 'Jose',
                'mname'       => 'D.',
                'suffix'      => 'Jr.',
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '04-0311',
            ],
            [
                'lname'       => 'DE LEON',
                'fname'       => 'Reanne',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1211',
            ],
            [
                'lname'       => 'DEL ROSARIO',
                'fname'       => 'Rodel',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-1113',
            ],
            [
                'lname'       => 'DELA CRUZ',
                'fname'       => 'Jenelyn',
                'mname'       => 'D.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '19-0219',
            ],
            [
                'lname'       => 'DELA CRUZ',
                'fname'       => 'Nita',
                'mname'       => 'M.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '19-0723',
            ],
            [
                'lname'       => 'DELA CRUZ',
                'fname'       => 'Jenny',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-1208',
            ],
            [
                'lname'       => 'DELA CRUZ',
                'fname'       => 'Eugene',
                'mname'       => 'N.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '15-0512',
            ],
            [
                'lname'       => 'DELA CRUZ',
                'fname'       => 'Arlen',
                'mname'       => 'A.',
                'suffix'      => null,
                'position'    => $supersrs,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '99-0801',
            ],
            [
                'lname'       => 'DIMACALE',
                'fname'       => 'Aileen',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1034',
            ],
            [
                'lname'       => 'DIOCTON',
                'fname'       => 'Reynaldo',
                'mname'       => 'F.',
                'suffix'      => 'IV',
                'position'    => $ssrs,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '08-0503',
            ],
            [
                'lname'       => 'DUMALI',
                'fname'       => 'Kyron',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0219',
            ],
            [
                'lname'       => 'DUQUE',
                'fname'       => 'Ma. Johna',
                'mname'       => 'C.',
                'suffix'      => null,
                'position'    => $ssrs,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '98-0303',
            ],
            [
                'lname'       => 'ELEC',
                'fname'       => 'Venus',
                'mname'       => 'H.',
                'suffix'      => null,
                'position'    => $ssrs,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '03-0120',
            ],
            [
                'lname'       => 'ESPIRITU',
                'fname'       => 'Alessandra',
                'mname'       => 'E.',
                'suffix'      => null,
                'position'    => $sra,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-1029',
            ],
            [
                'lname'       => 'EVANGELISTA',
                'fname'       => 'Editha',
                'mname'       => 'V.',
                'suffix'      => null,
                'position'    => $srs2,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '17-0408',
            ],
            [
                'lname'       => 'EVANGELISTA',
                'fname'       => 'Angielyn',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-1110',
            ],
            [
                'lname'       => 'FABROS',
                'fname'       => 'Rhona Jane',
                'mname'       => 'B.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '20-0202',
            ],
            [
                'lname'       => 'FAJARDO',
                'fname'       => 'Leonida',
                'mname'       => 'S.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '03-0129',
            ],
            [
                'lname'       => 'GABATO',
                'fname'       => 'Precious Mae',
                'mname'       => 'C.',
                'suffix'      => null,
                'position'    => $srs2,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '19-1026',
            ],
            [
                'lname'       => 'GABATO',
                'fname'       => 'Marlo',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-1107',
            ],
            [
                'lname'       => 'GARCIA',
                'fname'       => 'Albert',
                'mname'       => 'L.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '17-0512',
            ],
            [
                'lname'       => 'GARCIA',
                'fname'       => 'Josue',
                'mname'       => 'T.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '10-0706',
            ],
            [
                'lname'       => 'GARCIA',
                'fname'       => 'Jayvee',
                'mname'       => 'A.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '16-0539',
            ],
            [
                'lname'       => 'GARCIA',
                'fname'       => 'Sandra',
                'mname'       => 'D.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '15-0844',
            ],
            [
                'lname'       => 'GARCIA',
                'fname'       => 'Marvin',
                'mname'       => 'B.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-1203',
            ],
            [
                'lname'       => 'GARCILLANO',
                'fname'       => 'Marlon',
                'mname'       => 'C.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '16-0315',
            ],
            [
                'lname'       => 'HERNANDEZ',
                'fname'       => 'Rico Jake',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0402',
            ],
            [
                'lname'       => 'IBRAO',
                'fname'       => 'Francess Alyssa',
                'mname'       => 'G.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-0936',
            ],
            [
                'lname'       => 'LABAO',
                'fname'       => 'Guddy Mark',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0503',
            ],
            [
                'lname'       => 'LIMON',
                'fname'       => 'Ella Crysler',
                'mname'       => 'L.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '16-1055',
            ],
            [
                'lname'       => 'MAGDADARO',
                'fname'       => 'Cristo Rey',
                'mname'       => 'C.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-0906',
            ],
            [
                'lname'       => 'MARCOS',
                'fname'       => 'Virginia',
                'mname'       => 'P.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '15-0622',
            ],
            [
                'lname'       => 'MARIñAS',
                'fname'       => 'Ronald',
                'mname'       => 'A.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '15-0907',
            ],
            [
                'lname'       => 'MARTILLANA',
                'fname'       => 'John Joward',
                'mname'       => 'A.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '19-1109',
            ],
            [
                'lname'       => 'MINIMO',
                'fname'       => 'Joyce Rizza Lyne Nicole',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $jo,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-0409',
            ],
            [
                'lname'       => 'MIRANDA',
                'fname'       => 'Ma. Luisa',
                'mname'       => 'A.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-0731',
            ],
            [
                'lname'       => 'MUNAR',
                'fname'       => 'Benson',
                'mname'       => 'Z.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-0738',
            ],
            [
                'lname'       => 'NARCA',
                'fname'       => 'Eduard',
                'mname'       => 'P.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '12-0111',
            ],
            [
                'lname'       => 'NARCA',
                'fname'       => 'Reymark',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-0651',
            ],
            [
                'lname'       => 'NARCA',
                'fname'       => 'Emelita',
                'mname'       => 'D.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '18-1129',
            ],
            [
                'lname'       => 'NARCA',
                'fname'       => 'Roberto',
                'mname'       => null,
                'suffix'      => 'Jr.',
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0716',
            ],
            [
                'lname'       => 'NERI',
                'fname'       => 'Alberto',
                'mname'       => 'P.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '11-0208',
            ],
            [
                'lname'       => 'OMANDAM',
                'fname'       => 'Al Jun',
                'mname'       => 'B.',
                'suffix'      => null,
                'position'    => $sra,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0906',
            ],
            [
                'lname'       => 'ORDONIO',
                'fname'       => 'Reynante',
                'mname'       => 'L.',
                'suffix'      => null,
                'position'    => 'Career Scientist I',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '04-0903',
            ],
            [
                'lname'       => 'ORZAME',
                'fname'       => 'Rennoel',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-1207',
            ],
            [
                'lname'       => 'OSOTEO',
                'fname'       => 'Arvie',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-0420',
            ],
            [
                'lname'       => 'PADRONES',
                'fname'       => 'April',
                'mname'       => 'P.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '16-1101',
            ],
            [
                'lname'       => 'PADRONES',
                'fname'       => 'Rosalie',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0609',
            ],
            [
                'lname'       => 'PASARDAN',
                'fname'       => 'Evelyn',
                'mname'       => 'T.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-0816',
            ],
            [
                'lname'       => 'PILIEN',
                'fname'       => 'Elsa',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-1231',
            ],
            [
                'lname'       => 'PLACIDO',
                'fname'       => 'Juanito',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '25-0407',
            ],
            [
                'lname'       => 'RAGASA',
                'fname'       => 'Oscar',
                'mname'       => 'S.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '03-0163',
            ],
            [
                'lname'       => 'RAGASA',
                'fname'       => 'Carmelyn',
                'mname'       => 'M.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '16-0717',
            ],
            [
                'lname'       => 'REGALA',
                'fname'       => 'Esther',
                'mname'       => null,
                'suffix'      => null,
                'position'    => 'N/A',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-0110',
            ],
            [
                'lname'       => 'REYES',
                'fname'       => 'Lyca Mae',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '23-1105',
            ],
            [
                'lname'       => 'ROMERO',
                'fname'       => 'Rizaldo',
                'mname'       => 'C.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '03-0407',
            ],
            [
                'lname'       => 'SALONGA',
                'fname'       => 'Angie Lynne',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0220',
            ],
            [
                'lname'       => 'SANCHEZ',
                'fname'       => 'Reyzaldy',
                'mname'       => null,
                'suffix'      => 'Jr.',
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-1102',
            ],
            [
                'lname'       => 'SANTOS',
                'fname'       => 'Rebecca',
                'mname'       => 'I.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-0420',
            ],
            [
                'lname'       => 'SIBULBORO',
                'fname'       => 'Luilene',
                'mname'       => 'M.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '18-0418',
            ],
            [
                'lname'       => 'SUPLIDO',
                'fname'       => 'Maria Eda Apple',
                'mname'       => 'A.',
                'suffix'      => null,
                'position'    => $ssrs,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '07-0106',
            ],
            [
                'lname'       => 'SURALTA',
                'fname'       => 'Roel',
                'mname'       => 'R.',
                'suffix'      => null,
                'position'    => 'Center Chief',
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '98-0307',
            ],
            [
                'lname'       => 'TANAID',
                'fname'       => 'Aradel Mae',
                'mname'       => 'B.',
                'suffix'      => null,
                'position'    => $sra,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0521',
            ],
            [
                'lname'       => 'VALDEZ',
                'fname'       => 'Joana Marie',
                'mname'       => 'D.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '19-1116',
            ],
            [
                'lname'       => 'VALEROZO',
                'fname'       => 'Jonalyn',
                'mname'       => 'N.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '19-0544',
            ],
            [
                'lname'       => 'VILLANUEVA',
                'fname'       => 'Myan Ace Paola',
                'mname'       => null,
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '24-0555',
            ],
            [
                'lname'       => 'YARCIA',
                'fname'       => 'Ephraim Dioeve',
                'mname'       => 'R.',
                'suffix'      => null,
                'position'    => $srs1,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '22-0714',
            ],
            [
                'lname'       => 'ABDALA',
                'fname'       => 'Richard',
                'mname'       => 'M.',
                'suffix'      => null,
                'position'    => $laborer,
                'phone'       => null,
                'address'     => null,
                'email'       => null,
                'employee_id' => '10-0715',
            ],
        ];

        foreach ($personnels as $personnel) {
            Personnel::factory()->create($personnel);
        }

        Personnel::factory()->count(10)->create();
    }
}
