import type { 
  User, ActivityItem, PendingItem, EventForm, FormSubmission,
  InventoryItem, InventoryTransaction, Equipment, EquipmentUsage,
  Experiment, FESRequest, RentalItem, RentalRequest,
  CertificateTemplate, Notification
} from '@/types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Dr. Maria Santos',
    email: 'm.santos@philrice.gov.ph',
    role: 'admin',
    department: 'Crop Biotechnology Center',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=maria',
    phone: '+63 912 345 6789',
    createdAt: '2023-01-15T08:00:00Z',
    lastLogin: '2024-03-04T09:30:00Z',
    isActive: true,
  },
  {
    id: '2',
    name: 'Engr. Juan Dela Cruz',
    email: 'j.delacruz@philrice.gov.ph',
    role: 'lab_manager',
    department: 'Molecular Biology Laboratory',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=juan',
    phone: '+63 913 456 7890',
    createdAt: '2023-02-20T08:00:00Z',
    lastLogin: '2024-03-04T08:15:00Z',
    isActive: true,
  },
  {
    id: '3',
    name: 'Ms. Ana Reyes',
    email: 'a.reyes@philrice.gov.ph',
    role: 'ict_manager',
    department: 'ICT Unit',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ana',
    phone: '+63 914 567 8901',
    createdAt: '2023-03-10T08:00:00Z',
    lastLogin: '2024-03-03T16:45:00Z',
    isActive: true,
  },
  {
    id: '4',
    name: 'Mr. Pedro Garcia',
    email: 'p.garcia@philrice.gov.ph',
    role: 'admin_assistant',
    department: 'Administrative Services',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=pedro',
    phone: '+63 915 678 9012',
    createdAt: '2023-04-05T08:00:00Z',
    lastLogin: '2024-03-04T07:30:00Z',
    isActive: true,
  },
  {
    id: '5',
    name: 'Dr. Lisa Chen',
    email: 'l.chen@philrice.gov.ph',
    role: 'researcher',
    department: 'Rice Breeding',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    phone: '+63 916 789 0123',
    createdAt: '2023-05-12T08:00:00Z',
    lastLogin: '2024-03-02T14:20:00Z',
    isActive: true,
  },
  {
    id: '6',
    name: 'Guest User',
    email: 'guest@example.com',
    role: 'guest',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=guest',
    createdAt: '2024-03-01T08:00:00Z',
    isActive: true,
  },
];

// Mock Activity Feed
export const mockActivities: ActivityItem[] = [
  {
    id: '1',
    user: mockUsers[0],
    action: 'approved',
    target: 'FES Request FES-2024-0156',
    timestamp: '2024-03-04T10:30:00Z',
    type: 'approve',
  },
  {
    id: '2',
    user: mockUsers[1],
    action: 'logged usage for',
    target: 'PCR Machine #001',
    timestamp: '2024-03-04T09:45:00Z',
    type: 'create',
  },
  {
    id: '3',
    user: mockUsers[2],
    action: 'created event form',
    target: 'Regional Crop Biotechnology Symposium',
    timestamp: '2024-03-04T09:00:00Z',
    type: 'create',
  },
  {
    id: '4',
    user: mockUsers[3],
    action: 'approved vehicle rental',
    target: 'Rental Request VR-2024-0089',
    timestamp: '2024-03-04T08:30:00Z',
    type: 'approve',
  },
  {
    id: '5',
    user: mockUsers[4],
    action: 'submitted',
    target: 'FES Request FES-2024-0157',
    timestamp: '2024-03-03T16:15:00Z',
    type: 'submit',
  },
  {
    id: '6',
    user: mockUsers[0],
    action: 'updated inventory item',
    target: 'DNA Extraction Kit (50 reactions)',
    timestamp: '2024-03-03T14:00:00Z',
    type: 'update',
  },
  {
    id: '7',
    user: mockUsers[1],
    action: 'completed experiment',
    target: 'Gene Expression Analysis - Sample Batch 23A',
    timestamp: '2024-03-03T11:30:00Z',
    type: 'update',
  },
  {
    id: '8',
    user: mockUsers[2],
    action: 'generated certificates for',
    target: 'Workshop on CRISPR Technology',
    timestamp: '2024-03-03T10:00:00Z',
    type: 'create',
  },
];

// Mock Pending Items
export const mockPendingItems: PendingItem[] = [
  {
    id: '1',
    type: 'fes_request',
    title: 'FES Request FES-2024-0157',
    requestor: 'Dr. Lisa Chen',
    submittedAt: '2024-03-03T16:15:00Z',
    priority: 'high',
  },
  {
    id: '2',
    type: 'fes_request',
    title: 'FES Request FES-2024-0158',
    requestor: 'Dr. Roberto Lim',
    submittedAt: '2024-03-03T14:30:00Z',
    priority: 'medium',
  },
  {
    id: '3',
    type: 'rental',
    title: 'Vehicle Rental VR-2024-0090',
    requestor: 'Ms. Sarah Johnson',
    submittedAt: '2024-03-03T10:00:00Z',
    priority: 'medium',
  },
  {
    id: '4',
    type: 'rental',
    title: 'Venue Rental VN-2024-0045',
    requestor: 'Dr. Michael Tan',
    submittedAt: '2024-03-02T16:00:00Z',
    priority: 'low',
  },
  {
    id: '5',
    type: 'form_submission',
    title: 'Registration for Crop Biotech Quiz Bee',
    requestor: 'Student Group - UPLB',
    submittedAt: '2024-03-02T09:30:00Z',
    priority: 'medium',
  },
];

// Mock Event Forms
export const mockEventForms: EventForm[] = [
  {
    id: '1',
    title: 'Regional Crop Biotechnology Symposium',
    description: 'Annual symposium bringing together researchers and practitioners in crop biotechnology.',
    status: 'published',
    eventDate: '2024-03-15T08:00:00Z',
    eventEndDate: '2024-03-15T17:00:00Z',
    location: 'DA-CBC Auditorium',
    fields: [],
    registrationsCount: 156,
    maxRegistrations: 200,
    createdBy: mockUsers[2],
    createdAt: '2024-02-01T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    allowMultipleSubmissions: false,
    requireApproval: false,
  },
  {
    id: '2',
    title: 'Crop Biotech Quiz Bee',
    description: 'Test your knowledge in crop biotechnology!',
    status: 'published',
    eventDate: '2024-03-20T08:00:00Z',
    eventEndDate: '2024-03-20T12:00:00Z',
    location: 'Training Hall B',
    fields: [],
    registrationsCount: 45,
    maxRegistrations: 50,
    createdBy: mockUsers[2],
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    allowMultipleSubmissions: false,
    requireApproval: true,
  },
  {
    id: '3',
    title: 'Workshop on CRISPR Technology',
    description: 'Hands-on workshop on CRISPR-Cas9 genome editing techniques.',
    status: 'expired',
    eventDate: '2024-02-10T09:00:00Z',
    eventEndDate: '2024-02-12T17:00:00Z',
    location: 'Molecular Biology Laboratory',
    fields: [],
    registrationsCount: 25,
    maxRegistrations: 25,
    createdBy: mockUsers[1],
    createdAt: '2024-01-10T08:00:00Z',
    updatedAt: '2024-02-01T10:00:00Z',
    allowMultipleSubmissions: false,
    requireApproval: true,
  },
  {
    id: '4',
    title: 'Bioinformatics Training 2024',
    description: 'Introduction to bioinformatics tools and techniques.',
    status: 'draft',
    eventDate: '2024-04-15T08:00:00Z',
    eventEndDate: '2024-04-19T17:00:00Z',
    location: 'ICT Laboratory',
    fields: [],
    registrationsCount: 0,
    maxRegistrations: 30,
    createdBy: mockUsers[2],
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
    allowMultipleSubmissions: false,
    requireApproval: true,
  },
];

// Mock Form Submissions
export const mockFormSubmissions: FormSubmission[] = [
  {
    id: '1',
    formId: '1',
    formTitle: 'Regional Crop Biotechnology Symposium',
    submitterName: 'Maria Clara',
    submitterEmail: 'm.clara@uplb.edu.ph',
    data: { affiliation: 'UPLB', dietary: 'None' },
    status: 'approved',
    submittedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    formId: '1',
    formTitle: 'Regional Crop Biotechnology Symposium',
    submitterName: 'Jose Rizal',
    submitterEmail: 'j.rizal@irri.org',
    data: { affiliation: 'IRRI', dietary: 'Vegetarian' },
    status: 'approved',
    submittedAt: '2024-03-01T11:00:00Z',
  },
  {
    id: '3',
    formId: '2',
    formTitle: 'Crop Biotech Quiz Bee',
    submitterName: 'Andres Bonifacio',
    submitterEmail: 'a.bonifacio@student.edu.ph',
    data: { team_name: 'BioTech Warriors', members: 4 },
    status: 'pending',
    submittedAt: '2024-03-03T14:00:00Z',
  },
];

// Mock Inventory Items
export const mockInventoryItems: InventoryItem[] = [
  {
    id: '1',
    name: 'DNA Extraction Kit (50 reactions)',
    description: 'Commercial DNA extraction kit for plant samples',
    sku: 'DNA-EXT-50',
    barcode: '8901234567890',
    category: 'Chemicals & Reagents',
    quantity: 25,
    minStock: 10,
    unitOfMeasure: 'kit',
    location: 'Cold Room A',
    shelf: 'A-12',
    cost: 15000,
    createdAt: '2023-01-15T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    name: 'PCR Tubes 0.2ml (Pack of 1000)',
    description: 'Thin-walled PCR tubes, RNase/DNase free',
    sku: 'PCR-TUBE-02',
    barcode: '8901234567891',
    category: 'Plasticware',
    quantity: 8,
    minStock: 5,
    unitOfMeasure: 'pack',
    location: 'Storage Room B',
    shelf: 'B-05',
    cost: 2500,
    createdAt: '2023-02-20T08:00:00Z',
    updatedAt: '2024-02-28T10:00:00Z',
  },
  {
    id: '3',
    name: 'Micropipette 100-1000µl',
    description: 'Adjustable volume micropipette, Eppendorf brand',
    sku: 'PIP-1000',
    barcode: '8901234567892',
    category: 'Laboratory Supplies',
    quantity: 3,
    minStock: 2,
    unitOfMeasure: 'piece',
    location: 'Equipment Cabinet C',
    shelf: 'C-01',
    cost: 18000,
    createdAt: '2023-03-10T08:00:00Z',
    updatedAt: '2024-02-15T10:00:00Z',
  },
  {
    id: '4',
    name: 'Agarose Powder 500g',
    description: 'Molecular biology grade agarose',
    sku: 'AGAR-500',
    barcode: '8901234567893',
    category: 'Chemicals & Reagents',
    quantity: 2,
    minStock: 3,
    unitOfMeasure: 'bottle',
    location: 'Chemical Storage',
    shelf: 'D-08',
    cost: 8500,
    createdAt: '2023-04-05T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '5',
    name: 'Microcentrifuge Tubes 1.5ml (Pack of 500)',
    description: 'Clear polypropylene tubes with snap cap',
    sku: 'MCT-15-500',
    barcode: '8901234567894',
    category: 'Plasticware',
    quantity: 15,
    minStock: 5,
    unitOfMeasure: 'pack',
    location: 'Storage Room B',
    shelf: 'B-06',
    cost: 1200,
    createdAt: '2023-05-12T08:00:00Z',
    updatedAt: '2024-02-20T10:00:00Z',
  },
];

// Mock Inventory Transactions
export const mockTransactions: InventoryTransaction[] = [
  {
    id: '1',
    itemId: '1',
    itemName: 'DNA Extraction Kit (50 reactions)',
    type: 'outgoing',
    quantity: 2,
    previousQuantity: 27,
    newQuantity: 25,
    personnel: mockUsers[4],
    reference: 'FES-2024-0150',
    notes: 'For Gene Expression Analysis project',
    createdAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '2',
    itemId: '2',
    itemName: 'PCR Tubes 0.2ml (Pack of 1000)',
    type: 'incoming',
    quantity: 10,
    previousQuantity: 3,
    newQuantity: 13,
    personnel: mockUsers[0],
    reference: 'PO-2024-0089',
    notes: 'Restocking from supplier',
    createdAt: '2024-02-28T14:00:00Z',
  },
  {
    id: '3',
    itemId: '4',
    itemName: 'Agarose Powder 500g',
    type: 'outgoing',
    quantity: 1,
    previousQuantity: 3,
    newQuantity: 2,
    personnel: mockUsers[4],
    reference: 'FES-2024-0152',
    notes: 'For gel electrophoresis',
    createdAt: '2024-02-27T09:00:00Z',
  },
];

// Mock Equipment
export const mockEquipment: Equipment[] = [
  {
    id: '1',
    name: 'PCR Thermal Cycler',
    model: 'Veriti 96-Well',
    manufacturer: 'Applied Biosystems',
    serialNumber: 'TC2024001',
    category: 'PCR & qPCR',
    location: 'Molecular Biology Lab - Room 101',
    description: '96-well thermal cycler for PCR amplification',
    specifications: '96 wells, 0.2ml block, Temperature range: 4-99°C',
    status: 'available',
    requiresTraining: true,
    createdAt: '2023-01-15T08:00:00Z',
    lastMaintenance: '2024-02-01T08:00:00Z',
    nextMaintenance: '2024-05-01T08:00:00Z',
  },
  {
    id: '2',
    name: 'Spectrophotometer',
    model: 'NanoDrop One',
    manufacturer: 'Thermo Fisher',
    serialNumber: 'ND2024002',
    category: 'Spectrophotometry',
    location: 'Analytical Lab - Room 102',
    description: 'Microvolume UV-Vis spectrophotometer for nucleic acid quantification',
    specifications: 'Wavelength range: 190-850nm, Sample volume: 1-2µl',
    status: 'in_use',
    requiresTraining: true,
    createdAt: '2023-02-20T08:00:00Z',
    lastMaintenance: '2024-01-15T08:00:00Z',
    nextMaintenance: '2024-04-15T08:00:00Z',
  },
  {
    id: '3',
    name: 'Centrifuge',
    model: '5424 R',
    manufacturer: 'Eppendorf',
    serialNumber: 'CF2024003',
    category: 'Centrifugation',
    location: 'Sample Prep Lab - Room 103',
    description: 'Refrigerated microcentrifuge',
    specifications: 'Max speed: 21,130 x g, Temperature range: -10 to 40°C',
    status: 'available',
    requiresTraining: false,
    createdAt: '2023-03-10T08:00:00Z',
    lastMaintenance: '2024-02-15T08:00:00Z',
    nextMaintenance: '2024-05-15T08:00:00Z',
  },
  {
    id: '4',
    name: 'Fluorescence Microscope',
    model: 'Eclipse Ts2',
    manufacturer: 'Nikon',
    serialNumber: 'FM2024004',
    category: 'Microscopy',
    location: 'Imaging Lab - Room 201',
    description: 'Inverted fluorescence microscope',
    specifications: 'Phase contrast, Fluorescence, Digital camera',
    status: 'maintenance',
    requiresTraining: true,
    createdAt: '2023-04-05T08:00:00Z',
    lastMaintenance: '2024-03-01T08:00:00Z',
    nextMaintenance: '2024-06-01T08:00:00Z',
  },
  {
    id: '5',
    name: 'qPCR System',
    model: 'QuantStudio 3',
    manufacturer: 'Applied Biosystems',
    serialNumber: 'QPCR2024005',
    category: 'PCR & qPCR',
    location: 'Molecular Biology Lab - Room 101',
    description: 'Real-time PCR system for quantitative analysis',
    specifications: '96-well, 5-color detection, Cloud connectivity',
    status: 'available',
    requiresTraining: true,
    createdAt: '2023-05-12T08:00:00Z',
    lastMaintenance: '2024-02-20T08:00:00Z',
    nextMaintenance: '2024-05-20T08:00:00Z',
  },
];

// Mock Equipment Usage
export const mockEquipmentUsage: EquipmentUsage[] = [
  {
    id: '1',
    equipmentId: '2',
    equipmentName: 'Spectrophotometer',
    user: mockUsers[4],
    purpose: 'DNA quantification for Gene Expression Analysis',
    projectCode: 'GEA-2024-023',
    startTime: '2024-03-04T09:00:00Z',
    status: 'active',
  },
  {
    id: '2',
    equipmentId: '1',
    equipmentName: 'PCR Thermal Cycler',
    user: mockUsers[4],
    purpose: 'PCR amplification for SNP analysis',
    projectCode: 'SNP-2024-015',
    startTime: '2024-03-04T08:30:00Z',
    endTime: '2024-03-04T11:30:00Z',
    duration: 180,
    status: 'completed',
  },
];

// Mock Experiments
export const mockExperiments: Experiment[] = [
  {
    id: '1',
    title: 'Gene Expression Analysis - Sample Batch 23A',
    description: 'RNA extraction and qPCR analysis of drought-responsive genes',
    researcher: mockUsers[4],
    projectCode: 'GEA-2024-023',
    startDate: '2024-03-01T08:00:00Z',
    expectedEndDate: '2024-03-10T17:00:00Z',
    status: 'in_progress',
    equipment: [mockEquipment[1], mockEquipment[4]],
    createdAt: '2024-03-01T08:00:00Z',
    updatedAt: '2024-03-04T10:00:00Z',
  },
  {
    id: '2',
    title: 'SNP Genotyping - Population Study',
    description: 'High-throughput SNP analysis of rice varieties',
    researcher: mockUsers[4],
    projectCode: 'SNP-2024-015',
    startDate: '2024-03-05T08:00:00Z',
    expectedEndDate: '2024-03-15T17:00:00Z',
    status: 'scheduled',
    equipment: [mockEquipment[0]],
    createdAt: '2024-02-28T08:00:00Z',
    updatedAt: '2024-03-01T10:00:00Z',
  },
  {
    id: '3',
    title: 'Fluorescence Imaging - Protein Localization',
    description: 'GFP-tagged protein localization study',
    researcher: mockUsers[1],
    projectCode: 'IMG-2024-008',
    startDate: '2024-02-20T08:00:00Z',
    expectedEndDate: '2024-02-25T17:00:00Z',
    actualEndDate: '2024-02-26T16:00:00Z',
    status: 'delayed',
    equipment: [mockEquipment[3]],
    createdAt: '2024-02-15T08:00:00Z',
    updatedAt: '2024-02-26T16:00:00Z',
  },
];

// Mock FES Requests
export const mockFESRequests: FESRequest[] = [
  {
    id: '1',
    reference: 'FES-2024-0156',
    requestor: {
      name: 'Dr. Roberto Lim',
      email: 'r.lim@philrice.gov.ph',
      phone: '+63 917 890 1234',
      affiliation: 'PhilRice',
      philriceId: 'PR-2019-045',
    },
    purpose: 'DNA extraction and PCR analysis for blast resistance screening',
    projectCode: 'BRS-2024-032',
    startDate: '2024-03-10',
    endDate: '2024-03-14',
    status: 'approved',
    items: [
      { id: '1', type: 'facility', itemId: '1', itemName: 'Molecular Biology Lab', quantity: 1 },
      { id: '2', type: 'equipment', itemId: '1', itemName: 'PCR Thermal Cycler', quantity: 1 },
      { id: '3', type: 'supply', itemId: '1', itemName: 'DNA Extraction Kit', quantity: 5 },
    ],
    approver: mockUsers[1],
    approverNotes: 'Approved for the specified period. Please coordinate with lab staff.',
    submittedAt: '2024-03-01T10:00:00Z',
    reviewedAt: '2024-03-02T09:00:00Z',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-02T09:00:00Z',
  },
  {
    id: '2',
    reference: 'FES-2024-0157',
    requestor: {
      name: 'Dr. Lisa Chen',
      email: 'l.chen@philrice.gov.ph',
      phone: '+63 916 789 0123',
      affiliation: 'PhilRice',
      philriceId: 'PR-2020-078',
    },
    purpose: 'Gene expression analysis for drought stress response study',
    projectCode: 'GEA-2024-023',
    startDate: '2024-03-15',
    endDate: '2024-03-20',
    status: 'submitted',
    items: [
      { id: '1', type: 'facility', itemId: '1', itemName: 'Molecular Biology Lab', quantity: 1 },
      { id: '2', type: 'equipment', itemId: '2', itemName: 'Spectrophotometer', quantity: 1 },
      { id: '3', type: 'equipment', itemId: '4', itemName: 'qPCR System', quantity: 1 },
    ],
    submittedAt: '2024-03-03T16:15:00Z',
    createdAt: '2024-03-03T16:15:00Z',
    updatedAt: '2024-03-03T16:15:00Z',
  },
];

// Mock Rental Items
export const mockRentalItems: RentalItem[] = [
  {
    id: '1',
    type: 'vehicle',
    name: 'Toyota Hilux',
    description: '4x4 pickup truck for field activities',
    capacity: 5,
    rate: 2500,
    rateUnit: 'day',
    location: 'Motorpool',
    status: 'available',
    amenities: ['Air Conditioning', '4WD', 'GPS'],
  },
  {
    id: '2',
    type: 'vehicle',
    name: 'Toyota Hiace',
    description: '15-seater van for group transport',
    capacity: 15,
    rate: 3500,
    rateUnit: 'day',
    location: 'Motorpool',
    status: 'in_use',
    amenities: ['Air Conditioning', 'Audio System'],
  },
  {
    id: '3',
    type: 'venue',
    name: 'Conference Room A',
    description: 'Main conference room with AV equipment',
    capacity: 50,
    location: 'Admin Building - 2nd Floor',
    status: 'available',
    amenities: ['Projector', 'Sound System', 'Whiteboard', 'WiFi'],
  },
  {
    id: '4',
    type: 'venue',
    name: 'Training Hall B',
    description: 'Training hall with flexible seating',
    capacity: 100,
    location: 'Training Center - Ground Floor',
    status: 'available',
    amenities: ['Projector', 'Sound System', 'Whiteboard', 'WiFi', 'Air Conditioning'],
  },
  {
    id: '5',
    type: 'hostel',
    name: 'Single Room',
    description: 'Private room with attached bathroom',
    capacity: 1,
    rate: 800,
    rateUnit: 'day',
    location: 'CBC Hostel - 2nd Floor',
    status: 'available',
    amenities: ['Air Conditioning', 'TV', 'WiFi', 'Attached Bathroom'],
  },
];

// Mock Rental Requests
export const mockRentalRequests: RentalRequest[] = [
  {
    id: '1',
    reference: 'VR-2024-0089',
    type: 'vehicle',
    item: mockRentalItems[0],
    requestor: mockUsers[4],
    startDate: '2024-03-10',
    endDate: '2024-03-12',
    purpose: 'Field data collection in Nueva Ecija',
    status: 'approved',
    totalCost: 7500,
    approvedBy: mockUsers[3],
    approvedAt: '2024-03-04T08:30:00Z',
    approvalNotes: 'Approved. Please coordinate with motorpool 1 day before.',
    createdAt: '2024-03-01T10:00:00Z',
    updatedAt: '2024-03-04T08:30:00Z',
  },
  {
    id: '2',
    reference: 'VR-2024-0090',
    type: 'vehicle',
    item: mockRentalItems[1],
    requestor: mockUsers[4],
    startDate: '2024-03-15',
    endDate: '2024-03-15',
    purpose: 'Transport for workshop participants',
    status: 'pending',
    createdAt: '2024-03-03T10:00:00Z',
    updatedAt: '2024-03-03T10:00:00Z',
  },
];

// Mock Certificate Templates
export const mockCertificateTemplates: CertificateTemplate[] = [
  {
    id: '1',
    name: 'Participation Certificate',
    description: 'Standard certificate for event participation',
    type: 'participation',
    design: {
      layout: 'landscape',
      primaryColor: '#3D5A40',
      secondaryColor: '#4A7C59',
    },
    fields: ['recipient_name', 'event_name', 'event_date', 'venue'],
  },
  {
    id: '2',
    name: 'Completion Certificate',
    description: 'Certificate for training/workshop completion',
    type: 'completion',
    design: {
      layout: 'landscape',
      primaryColor: '#3D5A40',
      secondaryColor: '#7A9E7E',
    },
    fields: ['recipient_name', 'training_title', 'completion_date', 'duration'],
  },
  {
    id: '3',
    name: 'Achievement Certificate',
    description: 'Certificate for outstanding achievement',
    type: 'achievement',
    design: {
      layout: 'portrait',
      primaryColor: '#D4AF37',
      secondaryColor: '#3D5A40',
    },
    fields: ['recipient_name', 'achievement_title', 'award_date', 'description'],
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    title: 'FES Request Approved',
    message: 'Your FES request FES-2024-0156 has been approved.',
    type: 'success',
    read: false,
    actionUrl: '/fes/requests/1',
    createdAt: '2024-03-02T09:00:00Z',
  },
  {
    id: '2',
    userId: '1',
    title: 'New Registration',
    message: 'New registration for Regional Crop Biotechnology Symposium.',
    type: 'info',
    read: false,
    actionUrl: '/forms/submissions/1',
    createdAt: '2024-03-01T14:00:00Z',
  },
  {
    id: '3',
    userId: '2',
    title: 'Equipment Maintenance Due',
    message: 'PCR Thermal Cycler maintenance is due in 7 days.',
    type: 'warning',
    read: true,
    actionUrl: '/laboratory/equipments/1',
    createdAt: '2024-02-28T10:00:00Z',
  },
];

// Helper function to get current user
export const getCurrentUser = (): User => mockUsers[0];

// Helper function to get stats for dashboard
export const getDashboardStats = (role: string) => {
  switch (role) {
    case 'admin':
      return [
        { title: 'Total Users', value: 156, icon: 'Users', trend: 12, trendLabel: 'this month', color: 'primary' as const },
        { title: 'Pending Approvals', value: 23, icon: 'Clock', trend: -5, trendLabel: 'from last week', color: 'warning' as const },
        { title: 'Active Events', value: 8, icon: 'Calendar', trend: 2, trendLabel: 'this month', color: 'success' as const },
        { title: 'Equipment in Use', value: 12, icon: 'Microscope', trend: 0, trendLabel: 'stable', color: 'info' as const },
      ];
    case 'lab_manager':
      return [
        { title: 'Equipment Available', value: 28, icon: 'CheckCircle', color: 'success' as const },
        { title: 'Active Experiments', value: 15, icon: 'FlaskConical', color: 'primary' as const },
        { title: 'Pending FES Requests', value: 7, icon: 'ClipboardList', color: 'warning' as const },
        { title: "Today's Usage", value: 23, icon: 'Activity', color: 'info' as const },
      ];
    case 'ict_manager':
      return [
        { title: 'Active Forms', value: 12, icon: 'FileText', color: 'primary' as const },
        { title: 'Total Submissions', value: 1245, icon: 'Send', trend: 15, trendLabel: 'this month', color: 'success' as const },
        { title: 'Certificates Generated', value: 567, icon: 'Award', color: 'info' as const },
        { title: 'Pending Reviews', value: 8, icon: 'Eye', color: 'warning' as const },
      ];
    case 'admin_assistant':
      return [
        { title: 'Pending Rentals', value: 12, icon: 'Car', color: 'warning' as const },
        { title: "Today's Events", value: 3, icon: 'Calendar', color: 'primary' as const },
        { title: 'Vehicle Bookings', value: 8, icon: 'Truck', color: 'info' as const },
        { title: 'Venue Reservations', value: 5, icon: 'Building', color: 'success' as const },
      ];
    default:
      return [
        { title: 'My Active Requests', value: 4, icon: 'FileText', color: 'primary' as const },
        { title: 'Upcoming Events', value: 2, icon: 'Calendar', color: 'success' as const },
        { title: 'Equipment Reservations', value: 1, icon: 'Microscope', color: 'info' as const },
        { title: 'Forms Submitted', value: 12, icon: 'CheckCircle', color: 'warning' as const },
      ];
  }
};

// User Role Labels
export const USER_ROLE_LABELS: Record<string, string> = {
  admin: 'Administrator',
  lab_manager: 'Laboratory Manager',
  ict_manager: 'ICT Manager',
  admin_assistant: 'Administrative Assistant',
  researcher: 'Researcher',
  guest: 'Guest',
};
