export const RESOURCE_STEP_CONFIG = {
    biofreezer: {
        key: 'biofreezer',
        label: 'Biofreezer',
        title: 'Biofreezer Units',
        description: 'Select the biofreezer units you need for sample storage. Start typing to find available units.',
        field: 'biofreezers',
        placeholder: 'Select available biofreezers',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Biofreezer'],
        params: { routeParams: { categoryName: 'Biofreezer' } },
        requestType: 'Biofreezer',
        errorMessage: 'Please select at least one biofreezer',
    },
    field_experimental_space: {
        key: 'field_experimental_space',
        label: 'Field Experimental Space',
        title: 'Field Experimental Spaces',
        description: 'Select the field experimental spaces you need. Start typing to find available spaces.',
        field: 'field_spaces',
        placeholder: 'Select available field spaces',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Field Experimental Space'],
        params: { routeParams: { categoryName: 'Field Experimental Space' } },
        requestType: 'Field Experimental Space',
        errorMessage: 'Please select at least one field space',
    },
    ict_equipment: {
        key: 'ict_equipment',
        label: 'ICT Equipment',
        title: 'ICT Equipment',
        description: 'Select the ICT equipment you\'ll need. Search by typing the equipment name.',
        field: 'ict_equipments',
        placeholder: 'Select available ICT equipment',
        apiLink: 'api.inventory.categories.public',
        params: { routeParams: { categoryName: 'ICT Equipment' } },
        requestType: 'ICT Equipment',
        errorMessage: 'Please select at least one ICT equipment',
    },
    ict_supplies: {
        key: 'ict_supplies',
        label: 'ICT Supplies',
        title: 'ICT Supplies',
        description: 'Select the ICT supplies or consumables you need. Start typing to find available items.',
        field: 'ict_supplies',
        placeholder: 'Select available ICT supplies',
        apiLink: 'api.inventory.categories.public',
        params: { routeParams: { categoryName: 'ICT Supplies' } },
        requestType: 'ICT Supplies',
        errorMessage: 'Please select at least one ICT supply',
    },
    iec_materials: {
        key: 'iec_materials',
        label: 'IEC Materials',
        title: 'IEC Materials',
        description: 'Select the IEC (Information, Education, Communication) materials you need.',
        field: 'iec_materials',
        placeholder: 'Select available IEC materials',
        apiLink: 'api.inventory.categories.public',
        params: { routeParams: { categoryName: 'IEC Materials' } },
        requestType: 'IEC Materials',
        errorMessage: 'Please select at least one IEC material',
    },
    laboratory_access: {
        key: 'laboratory_access',
        label: 'Laboratory Access',
        title: 'Laboratory Access',
        description: 'Choose the laboratory facilities you\'ll be accessing. Search to find available labs.',
        field: 'laboratory_access',
        placeholder: 'Select available laboratories',
        apiLink: 'api.inventory.laboratories.public',
        requestType: 'Laboratory Access',
        errorMessage: 'Please select at least one laboratory',
    },
    laboratory_consumables: {
        key: 'laboratory_consumables',
        label: 'Laboratory Consumables',
        title: 'Laboratory Consumables',
        description: 'Select the laboratory consumables you need for your experiments.',
        field: 'laboratory_consumables',
        placeholder: 'Select available consumables',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Laboratory Consumables'],
        params: { routeParams: { categoryName: 'Laboratory Consumables' } },
        requestType: 'Laboratory Consumables',
        errorMessage: 'Please select at least one consumable',
    },
    laboratory_equipment: {
        key: 'laboratory_equipment',
        label: 'Laboratory Equipment',
        title: 'Laboratory Equipment',
        description: 'Select the laboratory equipment you\'ll need for your research.',
        field: 'laboratory_equipments',
        placeholder: 'Select available laboratory equipment',
        apiLink: 'api.inventory.categories.public',
        params: { routeParams: { categoryName: 'Laboratory Equipment' } },
        requestType: 'Laboratory Equipment',
        errorMessage: 'Please select at least one laboratory equipment',
    },
    medicool: {
        key: 'medicool',
        label: 'Medicool',
        title: 'Medicool Units',
        description: 'Select the Medicool units you need for temperature-controlled storage.',
        field: 'medicool_units',
        placeholder: 'Select available Medicool units',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Medicool'],
        params: { routeParams: { categoryName: 'Medicool' } },
        requestType: 'Medicool',
        errorMessage: 'Please select at least one Medicool unit',
    },
    office_space: {
        key: 'office_space',
        label: 'Office Space',
        title: 'Office Spaces',
        description: 'Select the office spaces you need for your work.',
        field: 'office_spaces',
        placeholder: 'Select available office spaces',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Office Space'],
        params: { routeParams: { categoryName: 'Office Space' } },
        requestType: 'Office Space',
        errorMessage: 'Please select at least one office space',
    },
    office_supplies: {
        key: 'office_supplies',
        label: 'Office Supplies',
        title: 'Office Supplies',
        description: 'Select the office supplies you need for your project.',
        field: 'office_supplies',
        placeholder: 'Select available office supplies',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Office Supplies'],
        params: { routeParams: { categoryName: 'Office Supplies' } },
        requestType: 'Office Supplies',
        errorMessage: 'Please select at least one office supply',
    },
    parking_space: {
        key: 'parking_space',
        label: 'Parking Space',
        title: 'Parking Spaces',
        description: 'Select the parking spaces you need during your visit.',
        field: 'parking_spaces',
        placeholder: 'Select available parking spaces',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Parking Space'],
        params: { routeParams: { categoryName: 'Parking Space' } },
        requestType: 'Parking Space',
        errorMessage: 'Please select at least one parking space',
    },
    plant_growth_chamber: {
        key: 'plant_growth_chamber',
        label: 'Plant Growth Chamber',
        title: 'Plant Growth Chambers',
        description: 'Select the plant growth chambers you need for your research.',
        field: 'plant_growth_chambers',
        placeholder: 'Select available plant growth chambers',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Plant Growth Chamber'],
        params: { routeParams: { categoryName: 'Plant Growth Chamber' } },
        requestType: 'Plant Growth Chamber',
        errorMessage: 'Please select at least one plant growth chamber',
    },
    screenhouse_space: {
        key: 'screenhouse_space',
        label: 'Screenhouse Space',
        title: 'Screenhouse Spaces',
        description: 'Select the screenhouse spaces you need for plant experiments.',
        field: 'screenhouse_spaces',
        placeholder: 'Select available screenhouse spaces',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Screenhouse Space'],
        params: { routeParams: { categoryName: 'Screenhouse Space' } },
        requestType: 'Screenhouse Space',
        errorMessage: 'Please select at least one screenhouse space',
    },
    storage_space: {
        key: 'storage_space',
        label: 'Storage Space',
        title: 'Storage Spaces',
        description: 'Select the storage spaces you need for your materials or equipment.',
        field: 'storage_spaces',
        placeholder: 'Select available storage spaces',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Storage Space'],
        params: { routeParams: { categoryName: 'Storage Space' } },
        requestType: 'Storage Space',
        errorMessage: 'Please select at least one storage space',
    },
    tokens: {
        key: 'tokens',
        label: 'Tokens',
        title: 'Tokens',
        description: 'Select the tokens you need for facility access or services.',
        field: 'tokens',
        placeholder: 'Select available tokens',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Tokens'],
        params: { routeParams: { categoryName: 'Tokens' } },
        requestType: 'Tokens',
        errorMessage: 'Please select at least one token type',
    },
    utility_space: {
        key: 'utility_space',
        label: 'Utility Space',
        title: 'Utility Spaces',
        description: 'Select the utility spaces you need for your activities.',
        field: 'utility_spaces',
        placeholder: 'Select available utility spaces',
        apiLink: 'api.inventory.categories.public',
        whitelist: ['Utility Space'],
        params: { routeParams: { categoryName: 'Utility Space' } },
        requestType: 'Utility Space',
        errorMessage: 'Please select at least one utility space',
    },
};

export const REQUEST_FORM_STEPS = [
    { key: 'request_type', label: 'Request Type' },
    { key: 'requestor', label: 'Requestor Info' },
    { key: 'details', label: 'Request Details' },
    ...Object.values(RESOURCE_STEP_CONFIG).map(({ key, label }) => ({ key, label })),
    { key: 'terms', label: 'Terms & Conditions' },
];

export const STEP_TO_REQUEST_TYPE = Object.values(RESOURCE_STEP_CONFIG).reduce((map, config) => {
    map[config.key] = config.requestType;
    return map;
}, {});

export const END_TIME_REQUEST_TYPES = [
    'Biofreezer',
    'ICT Equipment',
    'Laboratory Equipment',
    'Medicool',
    'Plant Growth Chamber',
    'Laboratory Access',
    'Field Experimental Space',
    'Screenhouse Space',
    'Office Space',
    'Storage Space',
    'Utility Space',
];