import {
  LuCalendar,
  LuCalendarDays,
  LuClipboardList,
  LuCpu,
  LuFlag,
  LuFlaskConical,
  LuMicroscope,
  LuPackage,
} from "@/Components/Icons";

export const PUBLIC_SERVICES = Object.freeze([
  {
    id: "rentals",
    title: "Bookings & Rentals",
    description: "Reserve vehicles, venues, and equipment for your events",
    icon: LuCalendarDays,
    routeName: "rental.bookings.guest",
    color: "blue",
    visibilityKey: "rentals",
    guideKey: "rental-bookings-public",
  },
  {
    id: "forms",
    title: "Event Registration",
    description: "Register and participate in DA-CBC events and activities",
    icon: LuCalendar,
    routeName: "forms.guest.index",
    color: "violet",
    visibilityKey: "forms",
    guideKey: "event-forms-guest",
  },
  {
    id: "fes",
    title: "FES Requests",
    description: "Request facilities, equipment, and supplies",
    icon: LuClipboardList,
    routeName: "labReq.guest.index",
    color: "amber",
    visibilityKey: "fes",
    guideKey: "fes-request-guest",
  },
  {
    id: "equipment-logger",
    title: "Lab Equipment Log",
    description: "Track and manage laboratory equipment usage",
    icon: LuMicroscope,
    routeName: "laboratory.equipments.show",
    color: "emerald",
    visibilityKey: "equipment_logger",
    guideKey: "equipment-logger-guest",
  },
  {
    id: "ict-equipment-logger",
    title: "ICT Equipment Log",
    description: "Monitor ICT assets and equipment availability",
    icon: LuCpu,
    routeName: "ict.equipments.show",
    color: "cyan",
    visibilityKey: "equipment_logger",
    guideKey: "equipment-logger-guest",
  },
  {
    id: "supplies-checkout",
    title: "Supplies Checkout",
    description: "Request and track inventory and supply items",
    icon: LuPackage,
    routeName: "inventory.public.outgoing.index",
    color: "orange",
    visibilityKey: "supplies_checkout",
    guideKey: "supplies-checkout-guest",
  },
  {
    id: "incident-reports",
    title: "Incident Reports",
    description: "Report issues, damages, or maintenance needs",
    icon: LuFlag,
    routeName: "suppEquipReports.create.guest",
    color: "rose",
    visibilityKey: "incident_reports",
    guideKey: "incident-report-guest",
  },
  {
    id: "experiment-monitoring",
    title: "Experiment Log",
    description: "Monitor ongoing laboratory experiments and research",
    icon: LuFlaskConical,
    routeName: "laboratory.monitoring.guest",
    color: "indigo",
    visibilityKey: "experiment_monitoring",
    guideKey: "experiment-monitoring-guest",
  },
]);
