<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class CertificateBatchSummaryNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(private readonly array $context)
    {
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $eventTitle = $this->context['event_title'] ?? 'Event';
        $status = strtoupper((string) ($this->context['status'] ?? 'completed'));
        $summary = $this->context['summary'] ?? [];

        $message = (new MailMessage())
            ->subject("Certificate Batch {$status}: {$eventTitle}")
            ->greeting('Hello,')
            ->line("The certificate batch for {$eventTitle} is now {$status}.")
            ->line('Success count: ' . (int) ($summary['success'] ?? 0))
            ->line('Failure count: ' . (int) ($summary['fail'] ?? 0))
            ->action('Open Certificates', url('/apps/certificates'));

        if (!empty($this->context['error'])) {
            $message->line('Error: ' . $this->context['error']);
        }

        return $message->line('This email was generated by OneCBC Portal.');
    }
}
