<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class EquipmentLogLifecycleNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(private readonly array $context)
    {
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $equipmentName = $this->context['equipment_name'] ?? 'Equipment';
        $statusLabel = $this->context['status_label'] ?? 'updated';
        $personnelName = $this->context['personnel_name'] ?? 'Unknown user';
        $moduleLabel = $this->context['module_label'] ?? 'Equipment Logger';

        return (new MailMessage())
            ->subject("{$moduleLabel}: {$equipmentName} {$statusLabel}")
            ->greeting('Hello,')
            ->line("{$equipmentName} was {$statusLabel}.")
            ->line("Personnel: {$personnelName}")
            ->line('Open the equipment logger dashboard to review the live status, timing, and location context.')
            ->action('Open Equipment Logger', url('/apps/laboratory'))
            ->line('This email was generated by CBC-Apps.');
    }
}
