<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class FormResponseReceivedNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(private readonly array $context)
    {
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $eventTitle = $this->context['event_title'] ?? 'Event Form';
        $subformType = $this->context['subform_type'] ?? 'response';
        $participantName = $this->context['participant_name'] ?? 'A participant';

        return (new MailMessage())
            ->subject("{$eventTitle}: New {$subformType} response")
            ->greeting('Hello,')
            ->line("{$participantName} submitted a new {$subformType} response for {$eventTitle}.")
            ->line('Open the event forms module to review the latest response details and workflow state.')
            ->action('Open Event Forms', url('/apps/event-forms/' . ($this->context['event_id'] ?? '')))
            ->line('This email was generated by OneCBC Portal.');
    }
}
