<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class PersonnelRegistrationSubmittedNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(private readonly array $context)
    {
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $fullName = $this->context['full_name'] ?? 'New personnel registrant';
        $email = $this->context['email'] ?? 'No email provided';
        $employeeId = $this->context['employee_id'] ?? 'Not provided';
        $position = $this->context['position'] ?? 'Not provided';
        $personnelType = $this->context['personnel_type'] ?? 'Personnel';

        return (new MailMessage())
            ->subject('New Personnel Registration Submitted')
            ->greeting('Hello,')
            ->line("{$fullName} submitted a new personnel registration.")
            ->line("Type: {$personnelType}")
            ->line("Email: {$email}")
            ->line("Employee ID: {$employeeId}")
            ->line("Position: {$position}")
            ->line('Open the personnel registration queue to review the submission after email verification.')
            ->action('Open Personnel Registrations', url('/apps/inventory/personnels/registrations'))
            ->line('This email was generated by OneCBC Portal.');
    }
}
