<?php

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class SupplyCheckoutTriggeredNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(private readonly array $context)
    {
    }

    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        $itemName = $this->context['item_name'] ?? 'Inventory item';
        $quantity = $this->context['quantity'] ?? 0;
        $unit = $this->context['unit'] ?? '';
        $requester = $this->context['requester_name'] ?? 'Unknown requester';

        return (new MailMessage())
            ->subject('Supply Checkout Triggered')
            ->greeting('Hello,')
            ->line("A supply checkout was recorded for {$itemName}.")
            ->line("Quantity: {$quantity} {$unit}")
            ->line("Requester: {$requester}")
            ->line('Review the inventory transactions module for the latest stock position and audit trail.')
            ->action('Open Inventory Transactions', url('/apps/inventory/transactions'))
            ->line('This email was generated by OneCBC Portal.');
    }
}
