@php
    $requestForm = $request->request_form;
    $requester = $request->requester;
@endphp

<div style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.6;">
    <h2 style="margin-bottom: 12px;">Facilities, Equipment, and Supplies Request Update</h2>

    <p>Hello {{ $requester?->name ?: 'Requester' }},</p>

    @if ($event === 'overdue')
        <p>Your released request is now overdue based on the declared end schedule.</p>
    @else
        <p>Your request status is now <strong>{{ strtoupper($eventLabel) }}</strong>.</p>
    @endif

    <table style="border-collapse: collapse; width: 100%; margin: 16px 0;">
        <tr>
            <td style="padding: 8px; border: 1px solid #e5e7eb; width: 35%;"><strong>Request ID</strong></td>
            <td style="padding: 8px; border: 1px solid #e5e7eb;">{{ $request->id }}</td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #e5e7eb;"><strong>Purpose</strong></td>
            <td style="padding: 8px; border: 1px solid #e5e7eb;">{{ $requestForm?->request_purpose ?: 'N/A' }}</td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #e5e7eb;"><strong>Date of Use</strong></td>
            <td style="padding: 8px; border: 1px solid #e5e7eb;">
                {{ $requestForm?->date_of_use ?: 'N/A' }}
                @if ($requestForm?->date_of_use_end)
                    to {{ $requestForm->date_of_use_end }}
                @endif
            </td>
        </tr>
        <tr>
            <td style="padding: 8px; border: 1px solid #e5e7eb;"><strong>Time of Use</strong></td>
            <td style="padding: 8px; border: 1px solid #e5e7eb;">
                {{ $requestForm?->time_of_use ?: 'N/A' }}
                @if ($requestForm?->time_of_use_end)
                    to {{ $requestForm->time_of_use_end }}
                @endif
            </td>
        </tr>
    </table>

    @if ($request->approval_constraint)
        <p><strong>Special Conditions:</strong> {{ $request->approval_constraint }}</p>
    @endif

    @if ($request->disapproved_remarks)
        <p><strong>Remarks:</strong> {{ $request->disapproved_remarks }}</p>
    @endif

    @if ($event === 'overdue')
        <p>Please coordinate with the FES officer if the borrowed/requested resources have not yet been returned.</p>
    @endif

    <p style="margin: 20px 0;">
        <a href="{{ $requestUrl }}" style="display: inline-block; padding: 10px 16px; background: #1d4ed8; color: #fff; text-decoration: none; border-radius: 6px;">
            Open Request
        </a>
    </p>

    <p>This email was generated by OneCBC Portal.</p>
</div>
