<div style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.6;">
    <h2 style="margin-bottom: 12px;">Your personnel registration was approved</h2>

    <p>Hello {{ $registration->full_name ?: 'there' }},</p>

    <p>
        Your OneCBC personnel registration has been approved. Your CBC ID number is
        <strong>{{ $card['employee_id'] }}</strong>.
    </p>

    <p>
        We attached your rendered A7 ID card for printing. Please review the details below.
    </p>

    <ul>
        <li><strong>Name:</strong> {{ $card['full_name'] }}</li>
        <li><strong>CBC ID:</strong> {{ $card['employee_id'] }}</li>
        <li><strong>Course/Program/Strand/Major:</strong> {{ $card['course_program'] }}</li>
        <li><strong>Date issued:</strong> {{ $card['date_issued'] }}</li>
    </ul>

    <p>This email was generated by OneCBC Portal.</p>
</div>
