<div style="font-family: Arial, sans-serif; color: #1f2937; line-height: 1.6;">
    <h2 style="margin-bottom: 12px;">Verify your personnel registration</h2>

    <p>Hello {{ $registration->full_name ?: 'there' }},</p>

    <p>
        We received your OneCBC personnel registration request. Please verify your email address
        so the administrators can review and approve your registration.
    </p>

    <p style="margin: 20px 0;">
        <a href="{{ $verificationUrl }}" style="display: inline-block; padding: 10px 16px; background: #15803d; color: #fff; text-decoration: none; border-radius: 6px;">
            Verify Email Address
        </a>
    </p>

    <p>
        This verification link expires in 7 days. If you did not submit this request, you may ignore this email.
    </p>

    <p>This email was generated by OneCBC Portal.</p>
</div>
